frp sleep and split compile stage

diff --git a/move2docker/etc/service/frpc/run b/move2docker/etc/service/frpc/run
--- a/move2docker/etc/service/frpc/run
+++ b/move2docker/etc/service/frpc/run
@@ -2,7 +2,8 @@
 . /.denv
 if [[ "$FRPC" == 1 ]]; then
   echo "frpc enabled, start frpc"
-  exec frpc -c /etc/frp/frpc.ini
+  pkill frpc
+  frpc -c /etc/frp/frpc.ini || ( echo "frpc failed, wait 3600s" && sleep 3600)
 else
   echo "frpc not enabled, frpc down"
   sv down frpc
